# =================================================================
# Licensed Materials - Property of IBM
#
# (c) Copyright IBM Corp. 2021 All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# =================================================================

---
# tasks file for configure-bastion-properties

- name: Get nodes IP and store into yaml file
  ansible.builtin.script: tools/modify-bastion.py
  args:
    executable: python3
    
- name: 'Get Nodes IP, MAC address and store into yaml file'
  ansible.builtin.script: tools/modify-dhcp.py
  args:
    executable: python3

- name: Show contents of dir
  ansible.builtin.command:
    cmd: ls -l

- name: Copy cluster-template.yaml to /tmp/ocp-install-files
  ansible.builtin.copy:
    src: cluster-template.yaml
    dest: /tmp/ocp-install-files/cluster-template.yaml